import assert from "node:assert/strict";
import { test } from "node:test";
import { mkdtempSync, writeFileSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execFileSync } from "node:child_process";
import { manage, overview, fileDiff } from "../server/git.ts";

test("Git manager stages selectively, reviews history, manages branches and preserves stashes", async () => {
  const dir = mkdtempSync(join(tmpdir(), "citropy-git-"));
  const git = (...args) => execFileSync("git", args, { cwd: dir, encoding: "utf8" });
  try {
    assert.equal((await overview(dir)).repository, false);
    await manage(dir, "init");
    const empty = await overview(dir);
    assert.equal(empty.repository, true);
    assert.equal(empty.hasCommits, false);
    assert.equal(empty.mergeInProgress, false);
    assert.ok(empty.status.branch);
    assert.equal(empty.status.upstream, null);
    assert.equal(empty.branches.length, 0);
    git("config", "user.name", "Citropy Test"); git("config", "user.email", "test@example.invalid");
    writeFileSync(join(dir, "one.txt"), "first\n"); writeFileSync(join(dir, "two.txt"), "second\n");
    assert.ok((await fileDiff(dir, "one.txt", false))?.added);
    await manage(dir, "stage", "one.txt");
    await manage(dir, "unstage", "one.txt");
    assert.equal((await overview(dir)).status.files.find(f => f.path === "one.txt").staged, false);
    await manage(dir, "stage", "one.txt");
    writeFileSync(join(dir, "one.txt"), "unstaged edit\n");
    await manage(dir, "discardWorktree", "one.txt");
    assert.equal(readFileSync(join(dir, "one.txt"), "utf8"), "first\n");
    assert.equal((await overview(dir)).status.files.find(f => f.path === "one.txt").staged, true);
    await manage(dir, "commit", "First commit");
    assert.equal(git("ls-files").trim(), "one.txt");
    const first = await overview(dir);
    assert.equal(first.hasCommits, true);
    assert.equal(first.commits.length, 1);
    assert.equal(first.commits[0].subject, "First commit");
    const detail = await manage(dir, "show", first.commits[0].hash);
    assert.equal(detail.kind, "detail");
    assert.equal(detail.message, "First commit");
    assert.equal(detail.patches[0].path, "one.txt");
    assert.equal(detail.patches[0].hunks[0].lines[0].text, "first");
    assert.equal(first.branches.find(b => b.current).subject, "First commit");
    const base = first.status.branch;
    await manage(dir, "createBranch", "feature");
    assert.equal((await overview(dir)).status.branch, "feature");
    await manage(dir, "stageAll"); await manage(dir, "commit", "Second commit");
    assert.equal((await overview(dir)).commits.length, 2);
    assert.equal((await overview(dir, 1)).commits[0].subject, "First commit");
    writeFileSync(join(dir, "one.txt"), "changed\n");
    await manage(dir, "stash", "Work in progress");
    assert.equal(readFileSync(join(dir, "one.txt"), "utf8"), "first\n");
    assert.equal((await overview(dir)).stashes.length, 1);
    const stash = await manage(dir, "showStash", "stash@{0}");
    assert.equal(stash.kind, "detail");
    assert.ok(stash.patches.some(patch => patch.path === "one.txt"));
    await manage(dir, "applyStash", "stash@{0}");
    assert.equal(readFileSync(join(dir, "one.txt"), "utf8"), "changed\n");
    assert.equal((await overview(dir)).stashes.length, 1);
    await manage(dir, "dropStash", "stash@{0}");
    git("restore", "one.txt");
    await manage(dir, "switchBranch", base);
    await manage(dir, "merge", "feature"); await manage(dir, "deleteBranch", "feature");
    const remote = join(dir, "remote.git");
    git("init", "--bare", remote);
    await manage(dir, "addRemote", remote, 0, "origin");
    assert.equal((await overview(dir)).remotes[0].name, "origin");
    await manage(dir, "publish", "origin");
    assert.equal((await overview(dir)).branches.find(b => b.current).upstream, `origin/${base}`);
    assert.equal((await overview(dir)).status.upstream, `origin/${base}`);
    await manage(dir, "fetch");
    await manage(dir, "pull");
    await manage(dir, "push");
    await manage(dir, "removeRemote", "origin");
    assert.equal((await overview(dir)).remotes.length, 0);
    await assert.rejects(manage(dir, "createBranch", "--bad"));
    await assert.rejects(manage(dir, "show", "HEAD; echo bad"));
  } finally { rmSync(dir, { recursive: true, force: true }); }
});

test("Git overview distinguishes an unresolved merge from a repository ready to commit", async () => {
  const dir = mkdtempSync(join(tmpdir(), "citropy-git-merge-"));
  const git = (...args) => execFileSync("git", args, { cwd: dir, encoding: "utf8" });
  try {
    git("init", "-b", "main");
    git("config", "user.name", "Citropy Test");
    git("config", "user.email", "test@example.invalid");
    writeFileSync(join(dir, "shared.txt"), "initial\n");
    await manage(dir, "stageAll");
    await manage(dir, "commit", "Initial commit");
    await manage(dir, "createBranch", "feature");
    writeFileSync(join(dir, "shared.txt"), "feature version\n");
    await manage(dir, "stageAll");
    await manage(dir, "commit", "Feature change");
    await manage(dir, "switchBranch", "main");
    writeFileSync(join(dir, "shared.txt"), "main version\n");
    await manage(dir, "stageAll");
    await manage(dir, "commit", "Main change");
    await assert.rejects(manage(dir, "merge", "feature"));
    const conflicted = await overview(dir);
    assert.equal(conflicted.mergeInProgress, true);
    assert.equal(conflicted.status.files[0].index, "U");
    const conflictPatch = await fileDiff(dir, "shared.txt", false);
    assert.ok(conflictPatch.hunks.some(hunk => hunk.lines.some(line => line.text === "<<<<<<< HEAD")));
    await manage(dir, "abortMerge");
    assert.equal((await overview(dir)).mergeInProgress, false);
    assert.equal(readFileSync(join(dir, "shared.txt"), "utf8"), "main version\n");
    await assert.rejects(manage(dir, "merge", "feature"));
    writeFileSync(join(dir, "shared.txt"), "resolved\n");
    await manage(dir, "stageAll");
    const resolved = await overview(dir);
    assert.equal(resolved.mergeInProgress, true);
    assert.equal(resolved.status.files[0].index, "M");
    await manage(dir, "commit", "Merge feature");
    const merged = await overview(dir);
    assert.equal(merged.commits.length, 4);
    assert.ok(merged.commits.every(commit => /^[a-f0-9]{40}$/.test(commit.hash) && !Number.isNaN(Date.parse(commit.date))));
    assert.equal(merged.mergeInProgress, false);
    const detail = await manage(dir, "show", merged.commits[0].hash);
    assert.equal(detail.patches[0].path, "shared.txt");
    assert.ok(detail.patches[0].hunks[0].lines.some(line => line.text === "resolved"));
  } finally { rmSync(dir, { recursive: true, force: true }); }
});
